---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: application-openshift-pipelines-placement
  namespace: openshift-gitops
spec:
  numberOfClusters: 1
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - dev
