---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: maxscale
spec:
  template:
    spec:
      containers:
      - name: work
        image: busybox
        command: ["sleep",  "300"]
        resources:
          requests:
            memory: 500Mi
            cpu: 500m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      restartPolicy: Never
  backoffLimit: 4
  completions: 50
  parallelism: 50
