---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:subscription-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:subscription-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube:admin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:admin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
---
apiVersion: v1                    
kind: Namespace
metadata:
  name: policy-generator                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: policy-generator
  namespace: policy-generator
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - policy-generator
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-levenhagen-demo-policygenerator-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-levenhagen-demo-policygenerator
  namespace: ggithubcom-levenhagen-demo-policygenerator-ns
spec:
  type: Git
  pathname: 'https://github.com/levenhagen/demo-policygenerator.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: 
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policy-generator
  name: policy-generator-subscription-1
  namespace: policy-generator
spec:
  channel: ggithubcom-levenhagen-demo-policygenerator-ns/ggithubcom-levenhagen-demo-policygenerator
  placement:
    placementRef:
      kind: Placement
      name: policy-generator-placement-1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: policy-generator
  name: policy-generator-placement-1
  namespace: policy-generator
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'name'
              operator: 'In'
              values: 
                - 'local-cluster'
  clusterSets:
    - global
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: policy-generator
  name: global
spec:
  clusterSet: global
