---
apiVersion: v1
kind: Secret
metadata:
  name: aws
  namespace: open-cluster-management
  labels:
    cluster.open-cluster-management.io/type: aws
    cluster.open-cluster-management.io/credentials: ""
type: Opaque
stringData:
  aws_access_key_id: ""
  aws_secret_access_key: ""
  baseDomain: ""
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
  additionalTrustBundle: ""
