---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  customization:
    addPage: {}
    customLogoFile:
      name: ""
    developerCatalog:
      types:
        state: Enabled
    projectAccess: {}
    quickStarts: {}
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  plugins:
  - monitoring-plugin
  - networking-console-plugin
  - mce
  - acm
  - gitops-plugin
  - pipelines-console-plugin
  providers: {}
  route:
    hostname: ""
    secret:
      name: ""
  unsupportedConfigOverrides: null
